databases:
  - name: evolution-postgres
    databaseName: evolution
    user: evolution_user
    plan: basic-256

services:
  - type: redis
    name: evolution-redis
    plan: starter
    ipAllowList: []
    
  - type: web
    name: evolution-api
    env: docker
    plan: starter
    repo: https://github.com/fedeglanz/evolution-api
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVER_TYPE
        value: http
      - key: SERVER_PORT
        value: 8080
      - key: SERVER_URL
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: CORS_METHODS
        value: GET,POST,PUT,DELETE
      - key: CORS_CREDENTIALS
        value: true
      - key: LOG_LEVEL
        value: ERROR,WARN,INFO
      - key: LOG_COLOR
        value: true
      - key: LOG_BAILEYS
        value: error
      - key: DEL_INSTANCE
        value: false
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_CONNECTION_URI
        fromDatabase:
          name: evolution-postgres
          property: connectionString
      - key: DATABASE_CONNECTION_CLIENT_NAME
        value: evolution_exchange
      - key: DATABASE_SAVE_DATA_INSTANCE
        value: true
      - key: DATABASE_SAVE_DATA_NEW_MESSAGE
        value: true
      - key: DATABASE_SAVE_MESSAGE_UPDATE
        value: true
      - key: DATABASE_SAVE_DATA_CONTACTS
        value: true
      - key: DATABASE_SAVE_DATA_CHATS
        value: true
      - key: DATABASE_SAVE_DATA_LABELS
        value: true
      - key: DATABASE_SAVE_DATA_HISTORIC
        value: true
      - key: CACHE_REDIS_ENABLED
        value: true
      - key: CACHE_REDIS_URI
        fromService:
          name: evolution-redis
          type: redis
          property: connectionString
      - key: CACHE_REDIS_TTL
        value: 604800
      - key: CACHE_REDIS_PREFIX_KEY
        value: evolution
      - key: CACHE_REDIS_SAVE_INSTANCES
        value: false
      - key: CACHE_LOCAL_ENABLED
        value: false
      - key: CONFIG_SESSION_PHONE_CLIENT
        value: Evolution API
      - key: CONFIG_SESSION_PHONE_NAME
        value: Chrome
      - key: QRCODE_LIMIT
        value: 30
      - key: QRCODE_COLOR
        value: "#175197"
      - key: AUTHENTICATION_API_KEY
        value: F2BC57EB8FBCB89D7BD411D5FA9F5451
      - key: AUTHENTICATION_EXPOSE_IN_FETCH_INSTANCES
        value: true
      - key: LANGUAGE
        value: en
      - key: WEBHOOK_EVENTS_QRCODE_UPDATED
        value: true
      - key: WEBHOOK_EVENTS_MESSAGES_SET
        value: true
      - key: WEBHOOK_EVENTS_MESSAGES_UPSERT
        value: true
      - key: WEBHOOK_EVENTS_CONNECTION_UPDATE
        value: true
      - key: WEBHOOK_GLOBAL_ENABLED
        value: true
      - key: WEBHOOK_GLOBAL_URL
        value: https://n8n-automation-bhdl.onrender.com/webhook-test/whatsapp
      - key: WEBHOOK_EVENTS_SEND_MESSAGE
        value: true

  - type: web
    name: n8n-automation
    env: docker
    plan: starter
    repo: https://github.com/fedeglanz/evolution-api
    dockerfilePath: ./Dockerfile.n8n
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: evolution-postgres
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: evolution-postgres
          property: port
      - key: DB_POSTGRESDB_DATABASE
        value: n8n
      - key: DB_POSTGRESDB_USER
        fromDatabase:
          name: evolution-postgres
          property: user
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: evolution-postgres
          property: password
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: N8N_HOST
        generateValue: true
      - key: WEBHOOK_URL
        generateValue: true
      - key: N8N_METRICS
        value: true
      - key: N8N_LOG_LEVEL
        value: info
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Reloj.Picachu@1290
      - key: EXECUTIONS_DATA_PRUNE
        value: true
      - key: EXECUTIONS_DATA_MAX_AGE
        value: 336
      - key: N8N_ENCRYPTION_KEY
        value: bfc29aca1b6c2d8df13a1a9367f388f6

  - type: web
    name: whatsapp-bot-backend
    env: docker
    plan: starter
    repo: https://github.com/fedeglanz/evolution-api
    dockerfilePath: ./backend/Dockerfile.backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        fromDatabase:
          name: evolution-postgres
          property: connectionString
      - key: DATABASE_CONNECTION_URI
        fromDatabase:
          name: evolution-postgres
          property: connectionString
      - key: JWT_SECRET
        value: WhatsAppBot-SuperSecure-JWT-Key-2025-Change-In-Production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: EVOLUTION_API_URL
        value: https://evolution-api-jz3j.onrender.com
      - key: EVOLUTION_API_KEY
        value: F2BC57EB8FBCB89D7BD411D5FA9F5451
      - key: AUTHENTICATION_API_KEY
        value: F2BC57EB8FBCB89D7BD411D5FA9F5451
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4
      - key: OPENAI_MAX_TOKENS
        value: 150
      - key: OPENAI_TEMPERATURE
        value: 0.7
      - key: N8N_WEBHOOK_URL
        value: https://n8n-automation-bhdl.onrender.com/webhook-test/whatsapp
      - key: N8N_API_URL
        value: https://n8n-automation-bhdl.onrender.com
      - key: FRONTEND_URL
        generateValue: true
      - key: ADMIN_URL
        generateValue: true
      - key: CORS_ORIGIN
        generateValue: true
      - key: RATE_LIMIT_WINDOW
        value: 900000
      - key: RATE_LIMIT_MAX
        value: 100
      - key: RATE_LIMIT_AUTH_MAX
        value: 5
      - key: MAX_FILE_SIZE
        value: 10485760
      - key: UPLOAD_PATH
        value: ./uploads
      - key: LOG_LEVEL
        value: info
      - key: LOG_FILE
        value: ./logs/app.log
      - key: REDIS_URL
        fromService:
          name: evolution-redis
          type: redis
          property: connectionString
      - key: REDIS_TTL
        value: 3600
      - key: WEBHOOK_SECRET
        value: n8n-webhook-secret-2025-change-in-production
      - key: DEFAULT_PAGE_SIZE
        value: 20
      - key: MAX_PAGE_SIZE
        value: 100
      - key: ANALYTICS_ENABLED
        value: true
      - key: EMBEDDINGS_ENABLED
        value: true
      - key: CAMPAIGNS_ENABLED
        value: true
      - key: MULTI_INSTANCE_ENABLED
        value: true
      - key: STARTER_MAX_INSTANCES
        value: 1
      - key: STARTER_MAX_MESSAGES
        value: 1000
      - key: BUSINESS_MAX_INSTANCES
        value: 3
      - key: BUSINESS_MAX_MESSAGES
        value: 5000
      - key: ENTERPRISE_MAX_INSTANCES
        value: -1
      - key: ENTERPRISE_MAX_MESSAGES
        value: -1
      - key: BACKUP_ENABLED
        value: false
      - key: MERCADOPAGO_ACCESS_TOKEN
        sync: false
      - key: MERCADOPAGO_PUBLIC_KEY
        sync: false
      - key: MERCADOPAGO_SANDBOX
        value: true
      - key: BACKEND_URL
        value: https://whatsapp-bot-backend-fnte.onrender.com
      - key: STRIPE_SECRET_KEY
        sync: false

  - type: web
    name: whatsapp-bot-frontend
    env: static
    plan: free
    repo: https://github.com/fedeglanz/evolution-api
    buildCommand: cd frontend/whatsapp-bot-frontend && npm install && npm run build
    staticPublishPath: ./frontend/whatsapp-bot-frontend/dist
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, DELETE, OPTIONS
      - path: /*
        name: Access-Control-Allow-Headers
        value: Content-Type, Authorization
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: VITE_API_URL
        value: https://whatsapp-bot-backend-fnte.onrender.com